### ISSUE TITLE
VeraCrypt not working anymore after upgrade from 1.12-BETA to 1.12 

### ISSUE THREAD

**Issue by c0d3z3r0** [veracrypt/VeraCrypt#15]
After upgrade from 1.12-BETA to 1.12 Veracrypt doesn't find any language files or binaries (VeraCrypt Format.exe etc.) anymore on Windows 10

**Comment by idrassi** [comment]
Can you please check the content of the folder C:\Program Files\VeraCrypt? Is these any missing files after the 1.12 installation?

**Comment by c0d3z3r0** [comment]
No, all files are there

**Comment by c0d3z3r0** [comment]
The Problem also still exists after an upgrad to 1.13-BETA

**Comment by idrassi** [comment]
humm...strange...what error message do you have? 
Are you running 32-bit or 64-bit?
When you click "Settings -> Languages", no languages are listed?
if you click manually on VeraCrypt Format.exe, does it run?

**Comment by c0d3z3r0** [comment]
64-bit
Right, there are no other languages than english listed.
I can run any binary manually but not in VeraCrypt e.g. "Create Volume".

When I run the Setup.exe in C:/Program Files/VeraCrypt it stops with an error that the driver couldn't be unloaded but then VeraCrypt works - until a reboot; after a reboot I need to do this again

**Comment by idrassi** [comment]
Ok. Let go step by step.
First, I tried to reproduce your issue: I had a Windows 10 Pro machine encrypted using 1.12 and I upgraded it to 1.13-BETA. I had a bench of warning messages because of the bootloader version mismatch but everything worked as expected.

So, we can rule out a systematic upgrade bug.

The first thing to do is to check the version of the files on VeraCrypt program folder: right click on each file and check the file version displayed. Are they all identical? They should all display 1.13.

Also check the version of the file c:\Windows\System32\Drivers\veracrypt.sys. It should be the same version.

In this process, check that they are all correctly signed.

**Comment by c0d3z3r0** [comment]
Yep, all the files including veracrypt.sys have version 1.13.0.0

**Comment by idrassi** [comment]
At this stage, I don't have any clues...
Can you please install the final 1.13 version that I have just released? 
Before that, exit VeraCrypt that is present in the system try.

**Comment by c0d3z3r0** [comment]
I installed 1.13 but the Problem persists.
Screenshots:
1 VeraCrypt after upgrade and reboot
2 Missing languages
3/4 Clicked "Create Volume"
5/6 Setup from C:/Program Files/VeraCrypt
7 VeraCrypt after 5/6

![1](https://cloud.githubusercontent.com/assets/6205797/9155769/b915118c-3ec3-11e5-9201-8c6181ccf75e.jpg)
![2](https://cloud.githubusercontent.com/assets/6205797/9155771/b915ab1a-3ec3-11e5-964f-4baaf9148b30.jpg)
![3](https://cloud.githubusercontent.com/assets/6205797/9155770/b91516c8-3ec3-11e5-8b97-785685b88834.jpg)
![4](https://cloud.githubusercontent.com/assets/6205797/9155768/b912f4f6-3ec3-11e5-9ad1-dd9d0d34a1ee.jpg)
![5](https://cloud.githubusercontent.com/assets/6205797/9155772/b915f7e6-3ec3-11e5-9f2b-1f3fac49f2bf.jpg)
![6](https://cloud.githubusercontent.com/assets/6205797/9155773/b92aecb4-3ec3-11e5-93a3-6fd9153eaa8c.jpg)
![7](https://cloud.githubusercontent.com/assets/6205797/9155774/b92d8adc-3ec3-11e5-858a-c2312c8afd0d.jpg)

**Comment by idrassi** [comment]
I think I understand what is happening: for an unknown reason, the VeraCrypt process that is launched in your case at logon is the one in C:\Windows\System32 and not the one in C:\Program File\VeraCrypt.

In order to check if my hypothesis is correct, can you please launch Task Manager right after opening your session, find VeraCrypt in the list of processes and then right click on it and choose Properties. What path is displayed for the VeraCrypt process?

Can you please open Regedit check the content of the key "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run"? It should contain a VeraCrypt entry that has the value "C:\Program Files\VeraCrypt\VeraCrypt.exe" /q preferences /a logon (note the full path).

**Comment by c0d3z3r0** [comment]
Yeah, you're right. Closing VeraCrypt completely and running it from Program Files solves the Problem. Why do we need the one in System32?

**Comment by c0d3z3r0** [comment]
The registry value is correct after disabling and reenabling the background task in settings but I don't have a clue how and why the path became wrong.

**Comment by idrassi** [comment]
The VeraCrypt exe file in System32 is needed when using System Favorite because in this case we need to create a service that will run at boot in order to mount the system favorites.
If system favorites are not used or if system favorites are removed, the exe is removed from System32. 

So, the issue is linked to a wrong path in the registry. VeraCrypt always creates this registry with a full path so something else must have modified this key to remove the full path.

Anyway, now we know what happen and you can solve your issue easily. 
You can close this ticket and if it happens again open it so that we try to find who is modifying the registry.

**Comment by c0d3z3r0** [comment]
I use System Favorites so this explains the exe in System32.
The problem is solved now, thank you very much for your help! :-)

**Comment by chou111** [comment]
I had problem with my win10 PC, I fixed by using "reset my PC and kept file" feature in Win10.  VeraCrypt file will not open after it.  Task Manager showed that VeraCrypt is not directed to System32 hence I added the Key value in regedit.  After reboot, I still can not open my file.  I get this error message:
Operation failed due to on or more of the following:
- Incorrect Keyfiles
-incorrect volume PIM number
-Incroeect password
- Incoreect PRF
-Not a valid volume
source: MountVolumer:7763

Since I used the correct PW and Key file, I assume it has to do with the volume?
