### ISSUE TITLE
System favorite volumes won't mount on boot

### ISSUE THREAD

**Issue by peter099** [veracrypt/VeraCrypt#515]
My system favorites volumes won't mount on boot and i can't find why. The password is the same for all volumes, drive letters are available, and i have checked ‘Mount system favorite volumes when Windows starts’. I am using VeraCrypt 1.24 and my system is Windows 7 x64.

**Comment by peter099** [comment]
Still no solution, and still no support.

**Comment by peter099** [comment]
The EventViewer shows two errors:

First error:
A timeout was reached (30000 milliseconds) while waiting for the VeraCrypt System Favorites service to connect.

Second error:
The VeraCrypt System Favorites service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.

**Comment by idrassi** [comment]
That’s strange because it looks like the file "C:\Windows\System32\VeraCrypt.exe" is not recognized as a service.

Can you please check the details this file in Explorer? More specifically, can you please share its version, size and its description? Also if possible can you please share its hash (for example SHA256)?

This file should be the same as "c:\Program Filea\VeraCrypt\VeraCrypt.exe". If not, then I want to know what this file is.

To fix the problem, copying the file "c:\Program Filea\VeraCrypt\VeraCrypt.exe" to "C:\Windows\System32\VeraCrypt.exe" should be enough if my hypothesis is correct.

Looking forward for your feedback.

**Comment by peter099** [comment]
Copying Veracrypt.exe from 'c:\Program Files\VeraCrypt\'  to 'C:\Windows\System32\' fixed the issue. Now system favorites are mounting on boot. Thanks!

As for the file Veracrypt.exe properties in 'System32' they are these: https://i.imgur.com/YpBPpew.png. I don't know how to get the SHA256 hash.

Also, i compared both files with WinMerge, before replacing the one in 'System32', and the program showed the files as not the same.

**Comment by idrassi** [comment]
Thank you for the screenshot and the feedback. It indicates that then file in System32 is "VeraCrypt Format.exe" instead of " VeraCrypt.exe". This means that the update process of VeraCrypt somehow mixed up the file and this is strange especially that I have not seen this on any of the test machines or even my machines.
I will review the code to see if I missed something.

Meanwhile, what is the previous version of VeraCrypt that you were running before updating to 1.24?

**Comment by peter099** [comment]
I didn't update VeraCrypt. I reinstalled my Windows 7 and just downloaded the current version 1.24, then encrypted my system partition. As for the previous version i was using, i am not sure, probably was 1.23-Hotfix-2.

**Comment by idrassi** [comment]
That is even stranger...this definitely warrants an investigation. I will let you know the result of my investigation as soon as possible.

**Comment by idrassi** [comment]
I have found the cause of the issue and I pushed a fix (see https://github.com/veracrypt/VeraCrypt/commit/f56a8c49f90bda734110f5ee28b2c405b417b057).
This is a regression that warrant a Hotfix for version 1.24. I’m preparing to release it tomorrow.
Meanwhile, reinstalling VeraCrypt 1.24 on top of it self also fixes the issue.

**Comment by peter099** [comment]
Ok, thanks for update.

**Comment by MalteHillmann** [comment]
This problem isn't fixed until now, isn't it?
I have the same problem with clean installed Win 10 and VeraCrypt 1.24, downloaded 3 days ago.

**Comment by idrassi** [comment]
As I said above, reinstalling 1.24 version fixes the issue. Did you try this?

I should be able to publish 1.24-Hotfix1 that foxes this regression tomorrow.

**Comment by idrassi** [comment]
I have uploaded a preview of the 1.24-Hotfix1 version that contains the fix for the this issue to https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/.

Feedback is welcomed before if you can test this preview which should be the same as final 1.24-Hotfix1 if no issue found.

**Comment by peter099** [comment]
I installed the hotfix and so far i don't see any issues.

**Comment by mestredelta** [comment]
> 
> 
> Thank you for the screenshot and the feedback. It indicates that then file in System32 is "VeraCrypt Format.exe" instead of " VeraCrypt.exe". This means that the update process of VeraCrypt somehow mixed up the file and this is strange especially that I have not seen this on any of the test machines or even my machines.
> I will review the code to see if I missed something.
> 
> Meanwhile, what is the previous version of VeraCrypt that you were running before updating to 1.24?

Exactly same here. C:\Windows\System32\Veracrypt.exe with hash of Veracrypt Format.exe (sha256 
0AF515B1F71182026B35CBF27E341407B8F9767A97DD2A14560AA9AB2F1C30F2). Repaced and Solved!! Thanks a lot!

Windows 10 x64 UEFI recently installed (less than 1 month ago).
