### ISSUE TITLE
Can't mount a volume on macOS Sierra

### ISSUE THREAD

**Issue by venil7** [veracrypt/VeraCrypt#86]
After upgrading to macOS sierra volumes stopped mounting showing this error
<img width="431" alt="screen shot 2016-08-06 at 16 52 46" src="https://cloud.githubusercontent.com/assets/508022/17457671/66e00088-5bf6-11e6-8612-211df7c472a8.png">

I have Fuse 3.4.1 installed

**Comment by idrassi** [comment]
A similar issue was fixed on 1.18-BETA available at https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/ (look for VeraCrypt_1.18-BETA.dmg).
The associated commit is https://github.com/veracrypt/VeraCrypt/commit/faf00ca1e093f0240f3cc668532f38b15e268da3

Does it solve your issue?

**Comment by venil7** [comment]
No, I'm afraid it doesn't solve my issue
it asks me to install macfuse, while it's already installed
<img width="446" alt="screen shot 2016-08-06 at 17 39 48" src="https://cloud.githubusercontent.com/assets/508022/17457938/df6198cc-5bfc-11e6-94ed-5b54f540819e.png">

**Comment by idrassi** [comment]
Thank you for the confirmation.

**Comment by polyisobutylene** [comment]
I am having the same issue using version 1.18a on macOS sierra.

Have tried every release of OSXFUSE since 2.8 (I think only version 3.0 and greater work with macOS sierra) and nothing resolves the issue.

Can't find an installer for a version past 1.18a

**Comment by hamusi** [comment]
For me the solving of issue was proper uninstall of virtual box. As it seems there is some limit of devices on Sierra.
See: https://github.com/osxfuse/osxfuse/issues/315
