### ISSUE TITLE
Traveler Disk Setup Files can't be created due to error about distribution package being damaged (MSI Installer)

### ISSUE THREAD

**Issue by AshleyHow** [veracrypt/VeraCrypt#886]
# Expected behavior

Traveler Disk Setup files are created successfully in the chosen folder.
# Observed behavior

![image](https://user-images.githubusercontent.com/28279067/151819551-03bcf656-d592-4131-b6a4-5afae7b430d5.png)

I am using the 64-bit MSI installer (VeraCrypt_Setup_x64_1.25.7.msi), I have verified the SHA256 hash (12D999BCA2B97A4F268087139D1606183E0CDB11C4B046B6C6DC5F0F965C3FD2) to ensure the file is not corrupt. I am using this installer as it supports silent install via Microsoft Intune.

**I can confirm that the exe installer does not have this issue.**

Previous reports of this error suggested a certificate error but I'm not sure this is the case in this instance as the certificate path for the file looks ok.

![image](https://user-images.githubusercontent.com/28279067/151821153-256e64d2-697b-411c-8e90-e04dd0ad20e8.png)

# Steps to reproduce

1. Open VeraCrypt.
2. Click Tools.
3. Click Traveler Disk Setup.
4. Choose directory for traveler disk files
5. Click create
6. Error message appears 'This distribution package is damaged. Please try downloading it again (preferably from the official VeraCrypt website at https://www.veracrypt.fr).'

I have tested doing via both a standard user and administrator and get the same result.

# Screenshots

# Your Environment

Please tell us more about your environment

**VeraCrypt version:** 
1.25.7
**Operating system and version:** 
This happens on multiple PC's where VeraCrypt has just been installed.
Windows 10 20H2 Build 10941.1466
Windows 10 21H1 Build 10943.1466
**System type:** 
64-bit

**Comment by idrassi** [comment]
Thank you for reporting this.
The issue with MSI install was that it doesn't include files from other architectures (only x64 binaries exist) and also "VeraCrypt Setup.exe" was wrongly use a place holder for binaries.
I have implemented a fix (https://github.com/veracrypt/VeraCrypt/commit/ebb67499f1eda64d3a6f7705fe6ec0c5fd12a1e3) and now Travel Disk creation works. Only limitation is that it will contain only x64 binaries.

Below is a Beta build of upcoming 1.25.8 containing the fix (signed using official IDRIX certificate and with PGP signature using VeraCrypt official key). You can use it to validate that it works on your side too.

[VeraCrypt_Setup_x64_1.25.8_BETA.zip](https://github.com/veracrypt/VeraCrypt/files/7982781/VeraCrypt_Setup_x64_1.25.8_BETA.zip)

**Comment by idrassi** [comment]
The Release Candidate for version 1.25.8 and which contain the fix has been published to https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/Windows/.
Final 1.25.8 release should be out in few days if no issues discovered during testing.

**Comment by idrassi** [comment]
This has been fixed in version 1.25.9.

**Comment by idrassi** [comment]
@m44rkiz 

Thank you very much for this report. This regression was caused by a change in Microsoft code signing certificate that we failed to noticed. I have pushed a fix for this: https://github.com/veracrypt/VeraCrypt/commit/2aae142a2d2cd6b553c02b86544a7bf3505be93b

A new VeraCrypt release will be published in few days and it will include this fix.

**Comment by Kistras** [comment]
The error still seems to be there in 1.26.24 (64 bit).

![Image](https://github.com/user-attachments/assets/a2a50da9-5f61-40ee-8419-1d9a47193799)
![Image](https://github.com/user-attachments/assets/d5239ec7-b567-487a-841a-fc2f057239e1)

Attempted with:
1.26.24 Portable (empty folder is created, error arises)
1.26.24 Setup .exe (empty folder is created, error arises)
1.26.24 Setup .msi (folder with elements present on second screenshot is created, error still arises)

It seems that I might be doing something wrong, since 1.26.18 (portable) wasn't working either, creating an empty folder and failing with an error.

**Comment by VidiotGeek** [comment]
This issue is marked as closed but I have just encountered this error with VeraCrypt version 1.26.24. Tried with the PortableApps.com install, the direct download as well as the .exe install. Windows 10 Pro 22H2.
